version: "3.8"
services:

  nginx_proxy:
    build:
      context: ./dockerfiles/nginx_proxy/
      dockerfile: nginx_proxy
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./dockerfiles/nginx_proxy/nginxconf.conf:/etc/nginx/conf.d/default.conf
      - /Users/admin/.acme.sh/eth1.info/eth1.info.cer:/etc/nginx/myapp.crt
      - /Users/admin/.acme.sh/eth1.info/eth1.info.key:/etc/nginx/myapp.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web_app

  web_app:
    build:
      context: ./dockerfiles/web_app/
      dockerfile: web_app
    container_name: web_app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    build:
      context: ./dockerfiles/database/
      dockerfile: database
    container_name: database
    restart: always
    ports:
      - 27017:27017
